### ISSUE TITLE
Ready for 0.1.0 GitHub release

### ISSUE THREAD

**Issue by bobleesj** [scikit-package/scikit-package-conda-forge#40]
### GitHub release checklist:

- [x] All PRs/issues attached to the release are merged.
- [x] License information is verified as correct. If you are unsure, please comment below.
- [x] Successfully run any tutorial examples or do functional testing with the latest Python version.
- [x] Grammar and writing quality are checked (no typos).

Please tag the maintainer (e.g., @username) in the comment here when you are ready for the GitHub release. Include any additional comments necessary, such as version information and details about the pre-release here:

**Comment by bobleesj** [comment]
@sbillinge  ready for `0.0.1-rc.0` probably we can wait for our first-time `rc` release (GitHub release only) in https://github.com/scikit-package/scikit-package-system/issues/28 

Functional testing

```
package create conda-forge
You've downloaded /Users/imac/.cookiecutters/scikit-package-conda-forge
before. Is it okay to delete and re-download it? [y/n] (y): 
  [1/13] github_username_or_orgname (bobleesj): 
  [2/13] package_import_name (diffpy.pdfgui): 
  [3/13] github_repo_name (diffpy.pdfgui): 
  [4/13] version (3.1.0): 
  [5/13] min_python_version (3.11): 
  [6/13] project_short_description (Python package for doing science.):
  [7/13] project_full_description (This is a Python package for doing 
science.): 
  [8/13] license_file (LICENSE.rst): 
  [9/13] recipe_maintainers (sbillinge, bobleesj): 
  [10/13] build_requirements (): 
  [11/13] host_requirements (setuptools, setuptools-git-versioning 
>=2.0, pip): 
  [12/13] runtime_requirements (numpy): 
  [13/13] testing_requirements (pip, pytest): 
Done! meta.yaml file has been created under the new diffpy.pdfgui directory.
```

`meta.yaml`:

```
cat meta.yaml 
{% set name = "diffpy.pdfgui" %}
{% set version = "3.1.0" %}
{% set python_min = "3.11" %}

kage:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/diffpy_pdfgui/diffpy_pdfgui-3.1.0.tar.gz
  sha256: 2ac7c32f2c3687a063757db4d035d4d309c80f05498f468a8b9fa77c91462c2f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  build:

  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-git-versioning >=2.0
    - pip

  run:
    - python >={{ python_min }}
    - numpy

test:
  requires:
    - python {{ python_min }}
    - pip
    - pytest

  source_files:
    - tests

  commands:
    - pip check
    - pytest

about:
  home: https://github.com/diffpy.pdfgui/diffpy.pdfgui/
  summary: Python package for doing science.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  description: |
    This is a Python package for doing science.
  doc_url: http://diffpy.pdfgui.github.io/diffpy.pdfgui/
  dev_url: https://github.com/diffpy.pdfgui/diffpy.pdfgui/

extra:
  recipe-maintainers:
    - sbillinge
    - bobleesj
```
